### ISSUE TITLE
Missing bonds and an atom bonded to itself

### ISSUE THREAD

**Issue by samblau** [aoterodelaroza/critic2#32] opened 2019-12-12 19:47 UTC
Hi @aoterodelaroza,

I've written an automated workflow to print cube files with Q-Chem and then analyze them with Critic2, and I've run this workflow on over 25,000 optimized structures that are relevant to aqueous electrolyte reactions. I'm just starting to dig into the data and have found two systems that Critic2 isn't handling correctly which I've named neg (the molecule has a -1 total charge) and neut (the molecule is neutral). Here are links to zipped directories containing the XYZ, the cube, the critic output, and a screenshot pointing to the missing bond:

https://www.dropbox.com/s/ajqxwaxdrezxs5m/neg.zip?dl=0
https://www.dropbox.com/s/sikcf0qc92vjspb/neut.zip?dl=0

Let's start with the neut example. While the molecule has 18 bonds, Critic2 only finds 17, missing this near-linear CO bond:

<img width="770" alt="neut_missing" src="https://user-images.githubusercontent.com/7431223/70742529-9e229d80-1cd2-11ea-8e08-cb56945b8bf4.png">

In the neg example, Critic2 misses a different CO bond on the other side of the molecule:

<img width="847" alt="neg_missing" src="https://user-images.githubusercontent.com/7431223/70742173-c65dcc80-1cd1-11ea-8d15-5cf631e0b7f8.png">

and instead reports that the central carbon in the CO3 group is bonded to itself. 

Please let me know if I can provide any further information to help you diagnose and fix these issues. I will also let you know of further problematic cases I find as I dig deeper into the data. 

Thanks,
Sam

**Comment by aoterodelaroza** [comment] 2019-12-12 20:26
Thanks, Sam. This is great testing! The missing bonds I'm not surprised to see, because of the known poor performance of critic in locating critical points from fields defined on a grid. I made some progress with the implementation of the grid CP search using discrete Morse theory (the earlier Gyulassy paper without any chemistry in it is actually much clearer) but it'll still take several weeks, as I'm quite swamped with other stuff. As for the atom bonded to itself, that is likely caused by a spurious CP having both its eigenvectors trace gradient paths that end up in the same atom, but I'll take a look.

**Comment by samblau** [comment] 2021-03-03 21:43
hey @aoterodelaroza, hope things are going well. I just updated my critic workflow infrastructure for the first time since late 2019 and did a recompile in the process, and I figured I'd check back in about this. Were you ever able to track down the source of these missing bonds and improve the code? Thanks!

**Comment by aoterodelaroza** [comment] 2021-03-03 22:34
The source is the same as before: The current algorithm for finding
critical points does not work reliably with densities on a grid. The
obvious candidate for a solution is to implement the
Gyulassy method. Unfortunately, I have not had time to do this yet.

**Comment by mkhorton** [comment] 2021-03-04 02:42
I saw Guylassy published a library (BSD-licensed), https://github.com/sci-visus/MSCEER, I'm not sure if any of that would be useful to you for a reference implementation.

**Comment by aoterodelaroza** [comment] 2021-03-04 10:00
It is! It certainly looks better than topoMS. I'll try to find some
time to attempt this in the near future - it's been too long.

**Comment by mkhorton** [comment] 2021-05-08 01:59
>  I'll try to find some time to attempt this in the near future - it's been too long.

Hi @aoterodelaroza, just wondering if there was an update on this, no worries if not! Just excited to try it out :-) Having some gridded data where the current algorithm seems to reliably fail between pairs of atoms that, while not symmetrically equivalent, clearly should have equivalent bond paths but some are missing, and this seems to be the case even when significantly increasing grid resolution.

**Comment by aoterodelaroza** [comment] 2021-05-08 09:34
Also, if this method is implemented, it should have to pass a correctness test to be acceptable. It seems to me the papers' priorities are efficiency > consistency > correctness, and in my opinion it should be the other way around.

**Comment by mkhorton** [comment] 2021-05-08 21:03
Ah yes, this is disappointing indeed, but I'm thoroughly convinced by your explanation -- thank you for sharing this information and for your attempts. I agree that efficiency is the wrong priority; as you say, if you have to make a determination about these spurious points, it's not feasible for large-scale processing, where you need the correctness first and foremost.

**Comment by aoterodelaroza** [comment] 2022-06-15 13:07
Hi all. I've finally found some time to take a closer look into this problem, and wrote up [this](https://doi.org/10.1063/5.0090232). The article describes the problems mentioned above, and proposes a solution for the all-electron density, which I think fixes the problems you have encountered. The new interpolation method is accessed with the SMOOTHRHO option to LOAD. Four examples with QE, abinit, VASP, and Gaussian cube files are provided in the [manual](https://aoterodelaroza.github.io/critic2/examples/example_08_01_gridcps/). If you are still on this, please try the new keyword and let me know how it goes. Note, however, that it works only for all-electron densities.

**Comment by aoterodelaroza** [comment] 2022-06-15 13:17
For the examples you provided (thanks for keeping them in the dropbox all this time), these inputs work:
```
molecule neg.dens.0.cube
load neg.dens.0.cube smoothrho

auto discard "$1 < 1e-5"
cpreport neg.vmd graph
```
This gives the same topology:
```
* Critical point list, final report (non-equivalent cps)
  Topological class (n|b|r|c): 19(19) 18(18) 0(0) 0(0) 
  Poincare-Hopf sum: 1
```
for neg and neut. The output files:
[neut.cro.txt](https://github.com/aoterodelaroza/critic2/files/8909634/neut.cro.txt)
[neg.cro.txt](https://github.com/aoterodelaroza/critic2/files/8909636/neg.cro.txt)
and the molecular graphs look like this:
![neg](https://user-images.githubusercontent.com/7144781/173836357-f7305eed-bc1e-4402-a4f1-98d0805ebdae.png)

**Comment by aoterodelaroza** [comment] 2022-06-15 13:19
The covellite example mentioned in issue #7 is considered explicitly in the [example from the manual](https://aoterodelaroza.github.io/critic2/examples/example_08_01_gridcps/). All critical points were found and there are no more spurious self-bonding atoms.

**Comment by mkhorton** [comment] 2022-06-17 22:57
> If you are still on this, please try the new keyword and let me know how it goes. Note, however, that it works only for all-electron densities.

This is excellent work; thank you for the update and sharing the examples! This work has been on pause for lack of a reliable method, so it will be exciting to revisit it :)

**Comment by aoterodelaroza** [comment] 2022-06-18 23:00
OK! I'll close this as solved, then. Feel free to reopen if you find any problems.

**Closed by aoterodelaroza** 2022-06-18 23:00 UTC
