### ISSUE TITLE
Compilation issue due to missing module

### ISSUE THREAD

**Issue by franciscoadasme** [aoterodelaroza/critic2#37] opened 2020-11-26 16:19 UTC
Hey everyone,

I'm having the following issue during the compilation (full output attached):

```
...
gfortran -DPACKAGE_NAME=\"critic2\" -DPACKAGE_TARNAME=\"critic2\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"critic2\ 1.0\" -DPACKAGE_BUGREPORT=\"aoterodelaroza@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"critic2\" -DVERSION=\"1.0\" -I.    -I../src/cubpack -DDATADIR='"/usr/local/share"'  -DDATE='"Thu Nov 26 13:06:25 -03 2020"' -DCOMMIT='"(config) 1.0"' -g -O2 -ffree-form -ffree-line-length-none -fopenmp -fallow-argument-mismatch -c -o fieldseedmod.o fieldseedmod.f90
fieldseedmod.f90:23:7:

   23 |   use wfn_private, only: molden_type_unknown
      |       1
Fatal Error: Cannot open module file ‘wfn_private.mod’ for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [fieldseedmod.mod] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

This has happened on three different machines (Linux and MacOS). I don't know what I'm doing wrong as I used the default compilation instructions

```
autoreconf
./configure
make
```

The `configure` output (attached) seems ok, I think.

Thanks.

[configure.txt](https://github.com/aoterodelaroza/critic2/files/5604052/configure.txt)
[make.txt](https://github.com/aoterodelaroza/critic2/files/5604053/make.txt)

**Comment by aoterodelaroza** [comment] 2020-11-26 16:28
Sorry about that. I am migrating critic2 to the cmake build system,
and also using it so I don't catch these problems immediately
anymore. Hopefully, that'll be done soon. The problem is a missing
dependency in the Makefile.am. I've already pushed the fix. Can you
please pull and try again?

**Comment by franciscoadasme** [comment] 2020-11-26 18:13
Thanks for the quick reply. I confirm that it works now after the patch.

**Closed** 2020-11-26 21:28 UTC
